name: az-sandbox
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - azure-storage-blob
  - jupyterlab
  - black
  - flake8
  - pre-commit
  - azure-identity
  - azure-storage-file
  - faker
  - pandas
  - python-dotenv
  - pydantic
  - mypy
  - mlflow
  - nodejs
